### ISSUE TITLE
Native ads missed

### ISSUE THREAD

**Issue by kurtsergey** [appodeal/react-native-appodeal#1]
Is there plan to support Native ads?

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by krunalp1993** [comment]
@kurtsergey @perrosnk 

Looks like Appodeal has stopped supporting React Native lib. Btw, We are in the same room as you are. We are going to do it our self. 

Did you try to implement Native Ads? If yes, Tell me. If no, We are going to implement it by customizing this Lib.

**Comment by perrosnk** [comment]
@krunalp1993 No, I haven't found a solution to this. I am not able to implement Native ads, but I am desperately trying to find a way, so I you manage to do it please let me know. That would be great news!

**Comment by perrosnk** [comment]
@krunalp1993 Did you have any luck implementing it?
