### ISSUE TITLE
artifactory: Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by trickeyd** [appodeal/react-native-appodeal#101]
Hi - have updated react-native-appodeal to 3.0.2, and iOS is working perfectly, however when I try to build for android i get the following error:

```
* What went wrong:
Could not determine the dependencies of task ':app:dexBuilderProdRelease'.
> Could not resolve all task dependencies for configuration ':app:prodReleaseCompileClasspath'.
   > Could not resolve com.facebook.soloader:soloader:0.9.0+.
     Required by:
         project :app
      > Failed to list versions for com.facebook.soloader:soloader.
         > Unable to load Maven meta-data from https://artifactory.appodeal.com/appodeal/com/facebook/soloader/soloader/maven-metadata.xml.
            > Could not GET 'https://artifactory.appodeal.com/appodeal/com/facebook/soloader/soloader/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```

I have tried a few things, such as patching the lib to remove jCenter() but so far I have had no success. Any help would be appreciated.

**Comment by trickeyd** [comment]
If I navigate directly to https://artifactory.appodeal.com/appodeal/com/facebook/soloader/soloader/maven-metadata.xml, I am faced with a sign in request.

I have gone over and over the android integrations steps, and everything seems fine - Is it possible there is a publish setting to make artefacts public which was forgotten your end for this version?

<img width="980" alt="Screenshot 2023-02-10 at 08 40 14" src="https://user-images.githubusercontent.com/1107295/218044062-83b1057c-d241-42bb-b3fe-f0f67d313ced.png">

**Comment by staskochkin** [comment]
This issue is outdated. Following path: https://artifactory.appodeal.com/appodeal/com/facebook/soloader/soloader/maven-metadata.xml has been moved
