### ISSUE TITLE
Not using Admob still facing issue with native android build.

### ISSUE THREAD

**Issue by AamenaSaiyed** [appodeal/react-native-appodeal#102]
I have installed app but Its crashes cause at native android side it is asking for admob configuration but I am not using it SO please help me with that why this is coming even i have not opt for Google ad mob.
![Screenshot 2023-03-02 at 6 51 20 PM](https://user-images.githubusercontent.com/90598756/222440196-e3e9ba61-51f2-4af2-81d7-b71929a0d736.png)

**Comment by ThanhNguyen140797** [comment]
+1

**Comment by staskochkin** [comment]
Hello @AamenaSaiyed @ThanhNguyen140797. If you're adding `implementation 'com.appodeal.ads:sdk:3.0.2.+'` in your application `build.gradle` all recommended by Appodeal adapters will be installed. Some of them requires to extra installation them, like AdMob for example. Of course you are able to disable unwanted adapters by excluding them:
```groovy
implementation ('com.appodeal.ads:sdk:3.0.2.+') {
    exclude group: 'com.appodeal.ads.sdk.networks', module: 'admob'
}
```
But I would like to recommend to not exclude adapters to maximise your ad revenue. You can read more about integration steps in [our documentation](https://wiki.appodeal.com/en/android/get-started).
