### ISSUE TITLE
Could not find any version that matches com.appodeal.ads:sdk:3.0.2.+.

### ISSUE THREAD

**Issue by CaptainEboy** [appodeal/react-native-appodeal#103]
<img width="604" alt="Appodeal Error" src="https://user-images.githubusercontent.com/63905637/232280552-28395836-d30b-4023-8afa-242b57f2a8bd.png">
 I am getting the above error after integrating appodeal in my app, you can reproduce the error using the link below

https://github.com/CaptainEboy/Appodeal-2023

**Comment by FrSenpai** [comment]
It's the same for me, I tried to downgrade to 3.0.1 the library itself, not working
I also tried many things I saw In your repo @CaptainEboy

**Comment by CaptainEboy** [comment]
Yeah, i was able to finally fix it.

Was pushing to github as i was working on it.

Glad you were following along and it was able to work for you also

**Comment by CaptainEboy** [comment]
I also fixed a problem relating to the app crashing in the code

**Comment by CaptainEboy** [comment]
I have made the respository private as the problem has been fixed and it also contains some sensitive data
