### ISSUE TITLE
undefined is not an object (evaluating 'Appodeal.initializeWithApiKey')

### ISSUE THREAD

**Issue by vadermemo** [appodeal/react-native-appodeal#11]
This don´t work with 
"react": "16.2.0",
"react-native": "0.52.2",
---------------------------------------------
Xcode  Version 9.2 (9C40b)
---------------------------------------------
This is the stacktrace
undefined is not an object (evaluating 'Appodeal.initializeWithApiKey')
2018-02-01 20:25:49.474860-0600 appodealTest[23664:180237] undefined is not an object (evaluating 'Appodeal.initializeWithApiKey')
2018-02-01 20:25:49.478 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'Appodeal.initializeWithApiKey')

**Comment by Tamplier** [comment]
@vadermemo 
please ensure that you added Appodeal.framework to your project correctly:
https://www.appodeal.com/sdk/documentation?framework=35&full=1&integration=1&platform=4#p_5
Pay special attention to item 5.1.4

**Comment by vadermemo** [comment]
@Tamplier thanks for your quicly response, but after these steps I got another error, but now get it when I click  on menu Product > build  from Xcode

workspaces/react-native/testFBLogin/ios/FBAudienceNetwork.framework/FBAudienceNetwork(FNFDashTrackMetadata.o)
ld: 1677 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I think is a dependency error, because I use FB SDK too.

Another tip or trick?

Thanks in advance.
