### ISSUE TITLE
CocoaPods could not find compatible versions for pod "StackModules"

### ISSUE THREAD

**Issue by trickyc0d3r** [appodeal/react-native-appodeal#111]
Hi there! Trying to install pods but got this error. Any solutions?

**Comment by padge** [comment]
So that Podfile fix got me closer, but I still couldn't get my app to build because of this error:
```
❌  Undefined symbols for architecture arm64
┌─ Symbol: __swift_FORCE_LOAD_$_swiftCompatibility56
└─ Referenced from: __swift_FORCE_LOAD_$_swiftCompatibility56_$_APDAppLovinAdapter in libAPDAppLovinAdapter.a(AppLovinNetwork.o)
```
I tried adding a swift file + bridging header to my project but no luck 🤔.
