### ISSUE TITLE
SDK issues on Google Play

### ISSUE THREAD

**Issue by grapefruitlips** [appodeal/react-native-appodeal#113]
Hey, when uploading on Google Play with "react-native-appodeal": "3.0.2", you get SDK issues:
> com.google.android.gms:play-services-ads-lite:15.0.0
> This SDK version has been reported as outdated. Upgrade to a newer version (19.3.0+).
> 
> Starting from November 22, 2023 00:00 (UTC) you won't be able to release new versions which contain this SDK version.
> 
> com.google.android.gms:play-services-ads:15.0.0
> This SDK version has been reported as outdated. Upgrade to a newer version (19.4.0+).
> 
> This SDK version has a note from the SDK developer. Here's what the SDK developer told us:
> 
> This version is officially deprecated, and will soon disable ad loading. Please update to a new version. See https://developers.google.com/admob/android/deprecation for more details.
> 
> Starting from November 22, 2023 00:00 (UTC) you won't be able to release new versions which contain this SDK version.

I found the dependencies:

|    +--- com.appodeal.ads.sdk.networks:bidmachine:3.0.2.0
|    |    +--- io.bidmachine:ads.networks.amazon:2.1.5.7
|    |    |    \--- com.google.android.gms:play-services-ads:15.0.0
|    |    |         +--- com.google.android.gms:play-services-ads-base:15.0.0 -> 22.2.0 (*)
|    |    |         +--- com.google.android.gms:play-services-ads-identifier:[15.0.0,16.0.0) -> 18.0.1 (*)
|    |    |         +--- com.google.android.gms:play-services-ads-lite:15.0.0 -> 22.2.0 (*)
|    |    |         +--- com.google.android.gms:play-services-basement:[15.0.0,16.0.0) -> 18.2.0 (*)
|    |    |         +--- com.google.android.gms:play-services-gass:15.0.0
|    |    |         |    +--- com.google.android.gms:play-services-ads-base:15.0.0 -> 22.2.0 (*)
|    |    |         |    \--- com.google.android.gms:play-services-basement:[15.0.0,16.0.0) -> 18.2.0 (*)

How can I remove this Amazon network from bidmachine network in build.gradle?) Or force a newer version of play-services-ads? Thanks

**Comment by da2gl** [comment]
Hello @grapefruitlips,

We've been looking into your reported issue. To address it, you have two potential solutions:

**Option 1:** Upgrade the `play-services-ads` library to version `21.4.0`. If you are using AdMob, this update should occur automatically. You can add the following dependency to your project's build.gradle file:

```gradle
implementation 'com.google.android.gms:play-services-ads:21.4.0'
```

**Option 2:** Alternatively, you can exclude the Amazon Ads dependency from the BidMachine library as follows:
```gradle
implementation ('com.appodeal.ads:sdk:3.0.2.+') {
    exclude group: 'io.bidmachine', module: 'ads.networks.amazon'
}
```
We recommend considering the first option as the standard configuration. Disabling certain recommended adapters can potentially impact your revenue negatively.

Thank you.
