### ISSUE TITLE
Gradle Build Error - Unable to Resolve Dependency for Appodeal SDK

### ISSUE THREAD

**Issue by hi-kuldeep** [appodeal/react-native-appodeal#119]
Upon attempting to compile the app, we encountered the following error:

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> Could not find any version that matches com.appodeal.ads:sdk:3.2.1.+. Versions that do not match:
  - 3.0.1.1
  - 3.0.1.0
Required by: project :app

Our current environment setup is as follows:

React version: 18.2.0
React Native version: 0.73.0
React Native Appodeal version: 3.2.1
It appears that the specified version of the Appodeal SDK (3.2.1) is not being recognized during the compilation process. Despite specifying the version in our dependencies, the build process is unable to find a matching version of the SDK.

<img width="715" alt="Screenshot 2024-03-13 at 12 45 00 PM" src="https://github.com/appodeal/react-native-appodeal/assets/60335573/06c265ab-06df-4884-b1eb-853c94cf060a">

**Comment by aleRisposta42** [comment]
I'm having the same issue. I followed the installation guide and I'm getting the same error.

I'm using Node version 18 and React Native 0.74.

I installed the latest version of react-native-appodeal,

but when I try with older versions, specifically 3.0.1,

I get other errors. How can I fix this?

**Comment by edwardsifi** [comment]
I have the same error, it seems that this version of the Appodeal SDK does not exist.

**Comment by FSPinho** [comment]
It worked for me when I placed the repository at the top:
```gradle
repositories {
    maven { url "https://artifactory.appodeal.com/appodeal" } // <---
    google()
    mavenCentral()
}
```

**Comment by FSPinho** [comment]
It worked when I added the repository into `allprojects -> repositories` instead of `buildscript -> repositories` 😄
