### ISSUE TITLE
Update to SDK 3.3.0

### ISSUE THREAD

**Issue by animaonline** [appodeal/react-native-appodeal#120]
Hi, when are you planning to update to latest SDK?

**Comment by EvgeniaGorbacheva** [comment]
Hello! React Native plugin has been just released

**Comment by khanisak** [comment]
@animaonline are you successfully update the SDK to 3.3.x ? 

I face error on android after update to 3.3.1 and 3.3.0

`Could not resolve all files for configuration ':app:debugRuntimeClasspath'. > Failed to transform af-android-sdk-6.13.1.aar (com.appsflyer:af-android-sdk:6.13.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}. > Could not find af-android-sdk-6.13.1.aar (com.appsflyer:af-android-sdk:6.13.1). Searched in the following locations: https://artifactory.appodeal.com/appodeal/com/appsflyer/af-android-sdk/6.13.1/af-android-sdk-6.13.1.aar`

this error show up even on new fresh react native project.

seems like this file is missing in appodeal's artifactory 
https://artifactory.appodeal.com/appodeal/com/appsflyer/af-android-sdk/6.13.1/af-android-sdk-6.13.1.aar
