### ISSUE TITLE
App Tracking Transparency Support

### ISSUE THREAD

**Issue by animaonline** [appodeal/react-native-appodeal#129]
Does the React Native sdk support this?

I have added NSUserTrackingUsageDescription to my app’s Info.plist, however it won’t display the consent dialog.

**Comment by da2gl** [comment]
Hi @animaonline.
You can contact [our support team](https://faq.appodeal.com/en/articles/96628-technical-support).
They will help with solving your issue with consent logic.
Have a nice day.
