### ISSUE TITLE
Portrait Mode broken

### ISSUE THREAD

**Issue by UberMC** [appodeal/react-native-appodeal#13]
Hi,

app is locked in portrait mode, (androidmanifest + even tried react-native-force-orientation)
When a landscape reward ad is closed, the app glitches out pretty terribly, it rotates between Portrait and landscape a couple times, and 50% of the time it put the app in landscape mode, until the scene is pop'd (I'm using react-native-router-flux)

"How is this even possible?" that the device is rotating when it's locked.

**Comment by Tamplier** [comment]
@UberMC, could you share your manifest file? Did you notice if it happens with only one ad network or it doesn't depend on a network? Also, could you share your application? I want to investigate the log output.
