### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by UberMC** [appodeal/react-native-appodeal#14]
Works on emulator, after building, just crashes. Too lazy to adb it because
1) proguard doesn't work
2) app can't pull from admob even though appodeal dashboard says everything is linked, and admob has checkmarks very every mediation
3) This breaks my app and forces it into landscape.

Really hope you guys work out the bugs, I'll have to try this again when it's working.

**Comment by Tamplier** [comment]
@UberMC 
1. I answered you in another thread
2. Please contact our support team, they'll help you to check link status and fix any problems.
3. Another thread
