### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by stnmonroe** [appodeal/react-native-appodeal#15]
Getting this error...

![screen shot 2018-02-15 at 4 07 51 pm](https://user-images.githubusercontent.com/26311858/36283543-79d48714-126a-11e8-8cd6-6bae8074572a.png)

Even though I have RNAppodeal.a linked...

![screen shot 2018-02-15 at 2 08 32 pm](https://user-images.githubusercontent.com/26311858/36283721-ebca2a86-126a-11e8-9f14-e3d32f9e47aa.png)

Appodeal installs differently than many of the other packages I've used, and other packages that throw this error say make sure it's linked... I'm lost. Can anyone help me?

**Comment by UberMC** [comment]
Maybe header recursion?
