### ISSUE TITLE
Why Appodeal stopped supporting react native?

### ISSUE THREAD

**Issue by perrosnk** [appodeal/react-native-appodeal#21]
According to this [post](https://blog.appodeal.com/framework-policy-changes/) Appodeal has stopped supporting react native.
Why is that?

**Comment by azsidhu** [comment]
@perrosnk let me know if you find the answer :)

**Comment by Momazo7u7** [comment]
It was because only few people used the module and they needed the time that they spent in this module for other things.

**Comment by vadermemo** [comment]
> It was because only few people used the module and they needed the time that they spent in this module for other things.

few people? i dont think so!  so many developers are using this framework

**Comment by Momazo7u7** [comment]
> > It was because only few people used the module and they needed the time that they spent in this module for other things.
> 
> few people? i dont think so! so many developers are using this framework

Did you read the post? 

> By stopping developing the other external plugins below used by fewer than 10% of our publishers, our development team will be able to dedicate more time and focus in enhancing the performance of the Unity 3D and Corona plugins.

**Comment by tarouboy** [comment]
> > It was because only few people used the module and they needed the time that they spent in this module for other things.
> 
> few people? i dont think so! so many developers are using this framework

I think you can judge by the number of stars given.

**Comment by RodolfoGS** [comment]
React Native is the future of mobile apps, they should continue support
