### ISSUE TITLE
Appodeal Banner view isn’t showing ad when added on a specific place. 

### ISSUE THREAD

**Issue by aliasad106** [appodeal/react-native-appodeal#27]
With new update AppodealBannerview is not showing up in view hierarchy. Even not in the example provided. 
Callbacks on AppodealBannerView’s props are also not called.

**Comment by staskochkin** [comment]
@aliasad106 Hey! AppodealBannerView isn't completely implemented yet for Android platform. Please use static banners (top/bottom) instead.

**Comment by staskochkin** [comment]
@aliasad106 Hi! We added support of AppodealBanner in #29

**Comment by staskochkin** [comment]
I'll close this issue. Please open new issue if your problem still exists.
