### ISSUE TITLE
Menifest merger failed

### ISSUE THREAD

**Issue by AnkitStar761** [appodeal/react-native-appodeal#28]
I took a fresh react-native project with version 0.62. My node version is v12.13.0. Android studio version is 3.6.3 .I followed each single step to integrate sdk. When I try to run the app I get the error - 

`Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
	is also present at [com.appodeal.ads.sdk.networks:my_target:2.6.0.3] AndroidManifest.xml:11:18-44 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.
`

I tried to add tools:replace="android:allowBackup" as suggested. Then again I run the app and got another error - 

`Manifest merger failed : Attribute activity#com.applovin.adview.AppLovinInterstitialActivity@configChanges value=(orientation|screenSize) from [:react-native-appodeal] AndroidManifest.xml:66:13-59
	is also present at [com.applovin:applovin-sdk:9.11.1] AndroidManifest.xml:17:13-91 value=(orientation|screenSize|smallestScreenSize|screenLayout).
	Suggestion: add 'tools:replace="android:configChanges"' to <activity> element at AndroidManifest.xml:64:9-66:62 to override.
`
I again did as suggested but I keep getting menifest merger error again and again. Please let me know why this problem occur?

**Comment by staskochkin** [comment]
@AnkitStar761 Hey! Please try to add
``` xml
android:fullBackupContent="true"
tools:replace="android:fullBackupContent"
```
in `<application>` tag of *AndroidManifest.xml*

**Comment by AnkitStar761** [comment]
I tried it but no effect on the error.

**Comment by staskochkin** [comment]
@AnkitStar761 Could you please share your *AndroidManifest.xml*?

**Comment by AnkitStar761** [comment]
@staskochkin Here is my menifest - 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.demodeal" xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:fullBackupContent="true"
      tools:replace="android:fullBackupContent"
      android:networkSecurityConfig="@xml/network_security_config"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

**Comment by staskochkin** [comment]
@AnkitStar761 Are you using appodeal plugin from GitHub or are you add it from `npm` registry?
For now `npm` version is 2.5.15 and it's outdated. 
To get latest version from GitHub you should remove appodeal-plugin dependency from your *package.json*, remove *node_modules* and run 

``` javascript
yarn add react-native-appodeal@github:appodeal/react-native-appodeal
```

**Comment by staskochkin** [comment]
@AnkitStar761 Hi! Does you problem still exist?
