### ISSUE TITLE
NPM package outdated

### ISSUE THREAD

**Issue by dylancom** [appodeal/react-native-appodeal#30]
If you install with NPM it resolves to version 2.1.5 (published 3 years ago).
https://www.npmjs.com/package/react-native-appodeal

**Comment by staskochkin** [comment]
@dylancom Hey! We plan to add some features to plugin such as Consent Manager support and Banner Views before update package in NPM registry.

**Comment by staskochkin** [comment]
@dylancom  Hi! We updated Appodeal to 2.6.4 and added previously mentioned features. NPM version is up to date now.
