### ISSUE TITLE
CocoaPods could not find compatible versions for pod "APDPubnativeAdapter"

### ISSUE THREAD

**Issue by dylancom** [appodeal/react-native-appodeal#35]
It could find version 2.6.3 but not 2.6.4.1 since the update.
All the other adapters install correctly though.

```
[!] CocoaPods could not find compatible versions for pod "APDPubnativeAdapter":
  In Podfile:
    APDPubnativeAdapter (= 2.6.4.1)

None of your spec sources contain a spec satisfying the dependency: `APDPubnativeAdapter (= 2.6.4.1)`.
```

**Comment by staskochkin** [comment]
@dylancom Hey, we updated `APDPubnativeAdapter`. It should be available through CocoaPods main repo: [APDPubnativeAdapter](https://github.com/CocoaPods/Specs/blob/0b607e2ab94aaa70893f56f3f6329bcbf03996af/Specs/2/5/f/APDPubnativeAdapter/2.6.4.1/APDPubnativeAdapter.podspec.json)
Try to run 
``` shell
pod update
``` 
If you problem still exists please reopen this issue.
