### ISSUE TITLE
How does Consent Manager Work?

### ISSUE THREAD

**Issue by BenjErgizerBunny** [appodeal/react-native-appodeal#40]
I want to collect consent for users covered by GDPR and CCPA and I see Appodeal's consent manager is part of this package.  I've used it on the example app but I don't fully understand how it works.

1. Does it automatically show up if the user is located in a location covered by GDPR or CCPA

2. How can I test to make sure it's showing up properly based on the user's location?  I've tried changing my iOS simulator's location to France for example and I still don't see it popping up.

**Comment by staskochkin** [comment]
Hi @BenjErgizerBunny, Yes Appodeal's consent manager automatically show up if the user is located  in a location covered by GDPR or CCPA. Location is determine on backend by IP address. If you want to check that it's showing up properly you can use any **VPN** service.  
Also you can use (after you call `synchroniseConsent` method)
``` javascript
Appodeal.forceShowConsentDialog((consent, regulation) => {
    // Handle updated data
})
```
This method will shows popup for user from any location. But if you user is restricted by GDPR or CCPA, he/she will see consent dialog twice: first time on `synchroniseConsent` and second on `forceShowConsentDialog`

**Comment by BenjErgizerBunny** [comment]
Thanks for much for the explanation @staskochkin !  Do you know how I would go about styling the consent screen so the UI is inline with my app?  I think that will get me a higher "yes" rate.

**Comment by staskochkin** [comment]
Current version of Consent Manager does not support custom styling of UI. Because of Consent Manager is supported on native iOS and Android, Unity and React Native, Consent dialog is static HTML that is served by Appodeal's backend and rendered by explicit web view of Consent Manager SDK. This HTML can be modified without Consent Manager update, however this functional is private as far as i know.
Would you like to please contact our technical support team via intercom on appodeal.com or email: support@appodeal.com if you have any suggestions or improvements about consent manager.

**Comment by BenjErgizerBunny** [comment]
Great, thanks for the background!  Is there an easy way to still use Appodeal’s logic to determine when to display my own custom consent component and force the Consent Manager UI component not to display?

**Comment by staskochkin** [comment]
In current implementation when application calls `Appodeal.synchroniseConsent` plugin will synchronise consent, load and show dialog if needed. You can fork this plugin and remove loading and showing logic: [iOS](https://github.com/appodeal/react-native-appodeal/blob/98c9bf4f701e231f16d0c673d6e5ed53921916df/ios/RNAppodeal.m#L77), [Android](https://github.com/appodeal/react-native-appodeal/blob/98c9bf4f701e231f16d0c673d6e5ed53921916df/android/src/main/java/com/reactlibrary/RNAppodealModule.java#L92).
In this case consent manager will return info about user's restriction by GDPR or CCPA. But you need to store consent info by your self. 
Hope it helps!

**Comment by staskochkin** [comment]
I'll close this issue. If you have any questions regarding Consent Manager please open new one or contact our support team.
