### ISSUE TITLE
Change library package name android from com.reactlibrary to com.appodeal

### ISSUE THREAD

**Issue by marf** [appodeal/react-native-appodeal#41]
Hello,
I have noticed that the package name of the library is com.reactlibrary which is the default package name of newly created react libraries, could you please change it in the project with com.appodeal or something like that?
This may cause some package name complicates with other packages which have the same problem.

Thank you

**Comment by staskochkin** [comment]
Hello @marf! 
I've merged you PR into master branch and, but I've renamed it into `com.appodeal.rnappodeal`. This updates will be included in next release.
Thank you for feedback and your contribution!
