### ISSUE TITLE
more than one banner on a single screen

### ISSUE THREAD

**Issue by Astrejoe** [appodeal/react-native-appodeal#46]
from the documentation: 

> Appodeal Banner View can be used only after Appodeal SDK was initialised. You can use show only one banner on screen. Static banners (top or bottom) can't be used in one session with AppodealBanner.

Why is this? Are there plans to make multiple banners on a single screen available in the future?

(by the way, there's a small typo: I think you mean: "You can show only one banner" instead of "You can use show only one banner")

**Comment by staskochkin** [comment]
Hello @Astrejoe! There are no plans to support multiple banners. This is because of the high risks of ad placement's ban from ad networks and apps rejection from AppStore/Google Play. Displaying multiple banners is may cause app performance issues as well. 

> (by the way, there's a small typo: I think you mean: "You can show only one banner" instead of "You can use show only one banner")
I will fix it, thank you!
