### ISSUE TITLE
Placement ids aren't registered for Android

### ISSUE THREAD

**Issue by zoftify** [appodeal/react-native-appodeal#48]
Hi, thanks a lot for the plugin!

I noticed there is an issue related to the placements.
I have the same code for android & ios and registered the same placements for iOS and Android. iOS works like a charm, but Android placements aren't recognized:

![image](https://user-images.githubusercontent.com/56393200/90320379-84181980-df49-11ea-83aa-c3ac62de741a.png)

How can we fix that?

Cheers!

**Comment by staskochkin** [comment]
Hello @zoftify. I've checked that plugin is sent `placement` from JS to Android native SDK. I think that this issue is not related to plugin logic. Please contact our support team via [intercom](https://appodeal.com) or email `support@appodeal.com`. It should be a more convenient way to solve it.

**Comment by staskochkin** [comment]
@zoftify Thanks for log and code snippet. Looks like we missed placement for the `AppodealBanner` component on the Android platform. We will fix it in the next release.

**Comment by staskochkin** [comment]
Fix has been released in **2.7.4**
