### ISSUE TITLE
iOS 14+ Support

### ISSUE THREAD

**Issue by dylancom** [appodeal/react-native-appodeal#52]
_Starting in iOS 14, IDFA will be unavailable until an app calls the App Tracking Transparency framework to present the app-tracking authorization request to the end-user. If an app does not present this request, the IDFA will automatically be zeroed out which may lead to a significant loss in ad revenue._

We need to present the App Tracking Transparency authorization request alert and initialize the Appodeal SDK after it's completion. This seems clear with Objective-C or Swift, but I think we need some docs on how to do this with the React Native package.

[iOS 14+ Support](https://wiki.appodeal.com/en/ios/2-7-3-beta-ios-sdk-integration-guide/ios-14+-support)

**Comment by staskochkin** [comment]
Hello @dylancom! 
According to [the latest news from Apple](https://developer.apple.com/news/?id=hx9s63c5) apps will be required to obtain permission to track users starting early next year. I think we need to wait for more information from Apple. 
For now, I've found that [react-native-permissions package](https://github.com/react-native-community/react-native-permissions) already added support of `AppTrackingTransparency` framework. I think we will add an example of its integration with Appodeal in the next release of this plugin.

**Comment by perrosnk** [comment]
@dylancom @staskochkin have you found a solution on how to do this?
