### ISSUE TITLE
Does this work with Expo Managed Workflow?

### ISSUE THREAD

**Issue by abudhia-oyo** [appodeal/react-native-appodeal#55]
Please confirm if it would work with expo managed workflow or requires linking?

**Comment by Albermonte** [comment]
Won't work with Managed Workflow, you have to eject and configure it manually following the Readme

**Comment by salman-crossvision** [comment]
> Won't work with Managed Workflow, you have to eject and configure it manually following the Readme

@Albermonte it can work without ejecting. Check [#55](https://github.com/appodeal/react-native-appodeal/issues/85#issuecomment-1890684153)
