### ISSUE TITLE
AdMob tablet banners exceed height of 90

### ISSUE THREAD

**Issue by dylancom** [appodeal/react-native-appodeal#59]
In July I started to use adSize = 'tablet' for banners on iPad (with a fixed height of 90 in style).
I have noticed that several AdMob banners exceeded the height of 90 so they we're not shown completely (some parts cutoff).

As of 12 august I suddenly received an "Ad serving limit" which is still active. I'm starting to think that this might be the cause as wrong banner placement / overlapping things could also lead into a limit (as I read).

Could it be that sometimes an MRec or adaptive banner that can exceed a height of 90 is shown?

**Comment by staskochkin** [comment]
Hi @dylancom!
You have faced this issue on iOS or Android platform?

**Comment by dylancom** [comment]
@staskochkin on iOS

**Comment by staskochkin** [comment]
Appodeal is using 
```obj-c
/// Leaderboard size for the iPad. Typically 728x90.
GAD_EXTERN GADAdSize const kGADAdSizeLeaderboard;
```
As size of AdMob banners for iPads. The height of creatives is depends on advertising campaigns and AdMob algorithms. It can be more than 90. Appodeal SDK will crop it in this case because Appodeal banner container has fixed size 90.
