### ISSUE TITLE
IOS - CocoaPods could not find compatible versions for pod "Appodeal"

### ISSUE THREAD

**Issue by Tahriff** [appodeal/react-native-appodeal#61]
When trying to setup react-native-appodeal for the ios version of my react-native app, I encountered the following error after typing `pod install`. 

> CocoaPods could not find compatible versions for pod "Appodeal":
>   In snapshot (Podfile.lock):
>     Appodeal (= 2.7.4-Beta)
> 
>   In Podfile:
>     APDPubnativeAdapter (= 2.7.4.1) was resolved to 2.7.4.1, which depends on
>       Appodeal (= 2.7.4)
> 
>     RNAppodeal (from `../node_modules/react-native-appodeal`) was resolved to 2.7.4, which depends on
>       Appodeal (= 2.7.4-Beta)
> 
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * changed the constraints of dependency `Appodeal` inside your development pod `RNAppodeal`.
>    You should run `pod update Appodeal` to apply changes you've made.`

Here is a view of my package.json dependencies:

> "dependencies": {
>     "react": "16.13.1",
>     "react-native": "0.63.2",
>     "react-native-appodeal": "^2.7.4"
>   },

**Comment by staskochkin** [comment]
Hello @Tahriff! 
Looks like you are using `2.7.4` version of this plugin which depends on `Appodeal SDK 2.7.4-Beta`. Please try to update to the latest version of this plugin `2.7.5` which depends on `Appodeal 2.7.4`

**Comment by Tahriff** [comment]
Hi @staskochkin, 
Works like a charm with version 2.7.5. Thanks a lot !
