### ISSUE TITLE
App rejected from Amazon Store

### ISSUE THREAD

**Issue by Albermonte** [appodeal/react-native-appodeal#63]
I've just submitted my app to the Play Store and Amazon Store, while it was approved on the Play Store it was rejected on Amazon Store, the reason is the following:

> Adds icon to Home Screen for an Ad webview: App contains SDK which has the potential to create a shortcut into device home screen for an Ad webview.
> 
> In general, we consider apps that collect personally identifiable information, have advertising displayed outside of an application, or perform an unexpected action to be potential risks. Please refer to Amazon Appstore Distribution Agreement and Amazon Appstore Review Guidelines for guidance.
> 
> Many development frameworks may insert libraries into your Android project by default, and may be flagged by us as a potential risk. You may, or may not be using the functionality performed by these libraries, but they can still represent a risk to the user.
> 
> We encourage you to modify your app to address the issues above and then resubmit your app for consideration.

Any way to configure Appodeal to prevent this or remove the conflicting SDKs?

**Comment by staskochkin** [comment]
Hello, @Albermonte 
I would like to recommend to remove the next ad networks adapters: **Mintegral**, **YandexMobileAds**, **TapJoy**, and **OguryAds**

Example for Appodeal SDK 2.7.4 (plugin version 2.7.6) is
```groovy
dependencies {
    implementation ('com.appodeal.ads:sdk:2.7.4.+') {
        exclude group: 'com.appodeal.ads.sdk.networks', module: 'ogury'
        exclude group: 'com.appodeal.ads.sdk.networks', module: 'yandex'
    }
}
```

**Comment by Albermonte** [comment]
Thanks
