### ISSUE TITLE
event parameter values for eventlisteners are different for Rewarded video

### ISSUE THREAD

**Issue by vineetshetty** [appodeal/react-native-appodeal#64]
Just spent a lot of time debugging this. The eventlistener callback value for AppodealRewardedEvent.CLOSED for iOS and Android are different.

iOS sends an event called event.fullyWatched and android sends an event called event.isFinished. For clarity:

iOS
Appodeal.addEventListener(AppodealRewardedEvent.CLOSED, (event: any) =>
    console.log("Rewarded video closed: ", **event.fullyWatched**)
)

Android
Appodeal.addEventListener(AppodealRewardedEvent.CLOSED, (event: any) =>
    console.log("Rewarded video closed: ", **event.isFinished**)
)

Not sure about other parameters since this was the only one that I needed.

**Comment by staskochkin** [comment]
Hello @vineetshetty. Changes will be added in the next release.

**Comment by staskochkin** [comment]
@vineetshetty Changes have been added into react-native-appodeal@2.7.7

**Comment by vineetshetty** [comment]
Thank you!
