### ISSUE TITLE
what will be the different options for "placement name"?

### ISSUE THREAD

**Issue by Param-Harrison** [appodeal/react-native-appodeal#7]
It is used here in the documentation
Appodeal.show(adtypes, "placement_name");
@NazarKozak I tag you so that you will get the notification. I didn't get any reply so far in this package. So, don't have any other option than tagging the developer. 
Please help explaining a bit

**Comment by NazarKozak** [comment]
Hi Param! Sure, thanks for tagging. Sorry for no reply. 
Placement allows you to control ads with our dashboard (Segments section). It should be named with the same value as in placements (Segments). You can leave it empty if you are not using placements.

**Comment by Param-Harrison** [comment]
Ok, got it Thanks man. Since I understood the answer, I am marking the issue as closed.
