### ISSUE TITLE
[QUESTION] Do I need to synchronise after user consent? 

### ISSUE THREAD

**Issue by perrosnk** [appodeal/react-native-appodeal#72]
If I initialize like this: 

```javascript
Appodeal.synchroniseConsent('Your appKey', (consent: AppodealConsentStatus, regulation: AppodealConsentRegulation) => {
    // Initialise Appodeal SDK here
    Appodeal.initialize('Your appKey', adTypes);
})
```

and we haven't yet asked the user for consent or it's the first time that the user opens the app. Do I need to re-initialize Appodeal after we call this?

```javascript
Appodeal.forceShowConsentDialog((consent: AppodealConsentStatus, regulation: AppodealConsentRegulation) => {
    // Handle updated data
})
```

**Comment by staskochkin** [comment]
Hello @perrosnk. No, you don't. Appodeal will automatically detect a change of user consent if you call `Appodeal.forceShowConsentDialog` after Appodeal initialization.
