### ISSUE TITLE
Android - cannot upgrade further than 'com.appodeal.ads:sdk:2.6.3.+'

### ISSUE THREAD

**Issue by Tahriff** [appodeal/react-native-appodeal#77]
I've been using the react-native-package for a couple of month now. On Android, I've never been able to upgrade the SDK to a version higher than 2.6.3. 

I can use a higher react-native package, but on the build.gradle, but my app is crashing if I use a version higher than 2.6.3 here:
`implementation 'com.appodeal.ads:sdk:2.8.1.+'

I don't get any error thrown. The app is launching and closes instantly. Any clue on what might be the cause ? Any major changes after SDK 2.6.3 ?

**Comment by staskochkin** [comment]
@Tahriff Hello, please trying to update this plugin to the latest version (**2.10.1**)

**Comment by staskochkin** [comment]
Closed due too inactivity.
