### ISSUE TITLE
Disable network method is broken on iOS and Android

### ISSUE THREAD

**Issue by Watersdr** [appodeal/react-native-appodeal#78]
The Readme lists this instruction for disabling networks individually:
```js
// Disable network:
// Call this method before initilisation
Appodeal.disableNetwork("some_network");
```

The first issue is that the strings for each network are very hard to find in the docs. I was finally able to find them inside the iOS docs (but on in the Android ones) [here](https://wiki.appodeal.com/en/ios/2-9-1-ios-sdk-integration-guide/configure-sdk). But then these strings also don't work for either platform with react native so here we are 😄 

## iOS
If you try this on iOS you get the error that the method only expects 1 argument but receives 2.
Which you can see is the case if you look at `/src/RNAppodeal.ts`, it always passes 2 arguments down to `ios/RNAppodeal.m`, which only expects 1.

## Android
If you try it on android you get an error that the method expects a double, not a string. In the Android docs for Appodeal, this method takes an enum that's not even exposed on the react native side.

**Comment by staskochkin** [comment]
Hello @Watersdr! Thanks for feedback. This should be fixed in [2.10.0 release](https://www.npmjs.com/package/react-native-appodeal/v/2.10.0)
