### ISSUE TITLE
Warn on Initialize Appodeal

### ISSUE THREAD

**Issue by jacow** [appodeal/react-native-appodeal#84]
Hi, i'm trying to Initialize Appodeal. But why a few seconds later I got a warning like this? 

 _WARN  Sending `onRewardedVideoLoaded` with no listeners registered.
 WARN  Sending `onBannerLoaded` with no listeners registered.
 WARN  Sending `onNonSkippableVideoLoaded` with no listeners registered.
 WARN  Sending `onInterstitialLoaded` with no listeners registered._

Is there something missing or something wrong from my Initialize?
I'm doing the same just like on the readme file.

```
import {
    Appodeal,
    AppodealAdType
} from 'react-native-appodeal';

const adTypes = AppodealAdType.INTERSTITIAL | AppodealAdType.REWARDED_VIDEO | AppodealAdType.BANNER;
const consent = true;
Appodeal.initialize('appodeal_api_key_credential', adTypes, consent)
```

**Comment by staskochkin** [comment]
Hello, @jacow. This warnings are appeared in case that an app is not registering call-backs listeners. If you app logic doesn't need to listen Appodeal's callbacks you can just ignore such warnings.

**Comment by jacow** [comment]
Ok, thank you for the information.

But, when i try to load the banner why i's always failed.
I'm using banner view. And i add callback onAdFailedToLoad then i got this log,

 LOG  Banner view is failed to load

May you help me why it's happend ?

**Comment by phballer11** [comment]
Hello @jacow , I have the same issue for Banner always being failed to load. Did you ever figure out what was the issue?

**Comment by staskochkin** [comment]
Closed due to inactivity
