### ISSUE TITLE
expo integration

### ISSUE THREAD

**Issue by arsalan-arshad** [appodeal/react-native-appodeal#85]
how to integrate into expo react native

**Comment by Albermonte** [comment]
Read #55

**Comment by RoccoDocco** [comment]
Shouldn't it be possible now with `[Expo Dev Builds](https://docs.expo.dev/guides/config-plugins/)`?

**Comment by LombaxTech** [comment]
im curious about this too

**Comment by gabrielcantarin** [comment]
Hey guys does anyone succeed? I'd like to see the plugins you guys used for EXPO

**Comment by salman-ibrahim** [comment]
> Hey guys does anyone succeed? I'd like to see the plugins you guys used for EXPO

I have created a gist just for this, you can find it [here](https://gist.github.com/salman-ibrahim/660008506b25f164633bbb393244e013)

Feel free to implement this any way you like, but here is how I did it:

- create a `plugins/` directory at project root and add all the files, `network_security_config.xml`, `withAppodealBuildGradle.js`, `withAppodealGradle.js`, `withAppodealManifest.js` and `withTrustLocalCerts.js` inside `plugins/` directory.
- update the app.json to use all the plugins as follows:

```
...
"plugins": [
        ...
        ["./plugins/withAppodealBuildGradle.js"],
        ["./plugins/withAppodealGradle.js"],
        ["./plugins/withTrustLocalCerts.js"],
        [
            "./plugins/withAppodealManifest.js",
            {
                "metaData": {
                    "com.google.android.gms.ads.APPLICATION_ID": "your_admob_app_id",
                    "com.facebook.sdk.ApplicationId": "facebook_app_id",
                    "com.facebook.sdk.ClientToken": "meta_client_token"
                }
            }
        ]
    ],
...
```

I have kept each plugin for modifying one file only hance, 4 different files. Feel free to combine them into one if you want.

In my case I was doing it for the sake of flexibility so I added params to plugin directly from `app.json`, if you dont want to supply `metaData` from `app.json` feel free to modify `withAppodealManifest.js` to hard code them directly there.

### My Expo Environment
Expo SDK: 48
Flow: Managed
Appodeal NPM Package: `"react-native-appodeal": "^3.2.1",`
Node Version: 18.18.0 

#### Note
Your project will stop working in Expo Go after applying these plugins, make sure to run your project in development build afterwards.

Do not omit these values from manifest:
```
"com.google.android.gms.ads.APPLICATION_ID": "your_admob_app_id",
"com.facebook.sdk.ApplicationId": "facebook_app_id",
"com.facebook.sdk.ClientToken": "meta_client_token"
```

doing so will cause the app to crash at splash screen. If you want to exclude adMob or Meta SDK then follow the docs [here](https://docs.appodeal.com/android/get-started)

These configs are written to work with Android only. I would love to see if you can modify them to work with iOS as well.

**Comment by RoccoDocco** [comment]
Checking in after 3 years, sad to see that there is still no official config plugin for this.
