### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNAppodeal.initialize')

### ISSUE THREAD

**Issue by ghost** [appodeal/react-native-appodeal#90]
Hello,
I followed the installation instructions and during the initialization I get an error from the title (picture no. 1).

![image](https://user-images.githubusercontent.com/40274845/146689460-99f58809-5d42-4986-bbcf-2971087dfa97.png)

In the picture below (no. 2) are the changes that are made on the file package.json after installation process.
![image](https://user-images.githubusercontent.com/40274845/146689498-fb213345-261b-4902-9fbd-2c5eed59456a.png)
I added "tslib": "^2.3.1" manually with command ("npm install tslib"). I don't know why that lib is not automatically included.

In the picture (no. 3) are the changes of all files that i changed after installation process.
![image](https://user-images.githubusercontent.com/40274845/146689529-16319966-3530-4b1d-9cd9-8c58906629d8.png)

In the picture (no. 4) is the main problem (Line 90). Just basic stuff from your installation page.
![image](https://user-images.githubusercontent.com/40274845/146689644-24983bb6-b7ba-4e70-a1cc-293bd9c7f648.png)

Can you please tell me what i'm doing wrong.
Thanks,
Mladen

**Comment by staskochkin** [comment]
Hello, @Mladen4!
This error is reproducible on both iOS and Android?

**Comment by Mladen4** [comment]
I only tried it on android.

Thanks for the replay.

**Comment by staskochkin** [comment]
@Mladen4 Are you using expo? Did you extract app by using `expo eject`?

**Comment by Mladen4** [comment]
I'm using expo and i extracted it.
Also i tried with new clear app (create-react-native-app my-project)
without the expo and the error was the same.

**Comment by staskochkin** [comment]
@Mladen4 Could you please provide sample project where this issue is reproduced?

**Comment by staskochkin** [comment]
Closed due to inactivity
