### ISSUE TITLE
Expo Integration with new Development Builds

### ISSUE THREAD

**Issue by RoccoDocco** [appodeal/react-native-appodeal#94]
Expo Dev Builds allow custom [config plugins](https://docs.expo.dev/guides/config-plugins/) which lets you use native modules.
Could it be possible to integrate Appodeal with these config plugins while staying within the Expo Managed Workflow?

**Comment by salman-crossvision** [comment]
Check out this [gist](https://gist.github.com/salman-ibrahim/660008506b25f164633bbb393244e013)
